name: course
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - pandas
  - ipython
  - jupyterlab
  - pyyaml
  - jupyterlab_vim
  - jupyterlab-lsp
  - python-lsp-server
  - icecream
  - nltk
